name: Release Package
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create ~/.npmrc file (for publishing)
        run: |
          echo //npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }} >> ~/.npmrc |
          echo ${{ secrets.NPM_ORGANIZATION }}:registry=${{ secrets.NPM_REGISTRY }} >> ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run release
        run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.NPM_PACKAGE }}
